#!/data/data/com.termux/files/usr/bin/bash
# GrokHunter — Termux:X11 low-latency desktop integration

setup_termux_x11() {
  msg -t "Setting up Termux:X11 (low-latency desktop)"

  # 1. Install required packages in Termux
  msg -tn "Installing x11-repo, termux-x11-nightly and pulseaudio..."
  if pkg install -y x11-repo >/dev/null 2>&1 && \
     pkg install -y termux-x11-nightly pulseaudio >/dev/null 2>&1; then
    cursor -u1
    msg -ts "Termux:X11 packages installed"
  else
    cursor -u1
    msg -tw "Failed to install some X11 packages — run manually: pkg install x11-repo termux-x11-nightly pulseaudio"
  fi

  # 2. Robustly patch nethunter / nh launcher to bind Termux /tmp
  #    (required so X11 sockets are visible inside the proot)
  local launcher="${TERMUX_FILES_DIR}/usr/bin/nethunter"
  local shortcut="${TERMUX_FILES_DIR}/usr/bin/nh"
  local tmp_bind="-b /data/data/com.termux/files/usr/tmp:/tmp"

  for f in "${launcher}" "${shortcut}"; do
    if [[ -f ${f} ]]; then
      if grep -q "/data/data/com.termux/files/usr/tmp:/tmp" "${f}" 2>/dev/null; then
        msg -ts "${f##*/} already has /tmp bind"
        continue
      fi

      # Method A: insert after the first -b /dev line (most common pattern)
      if grep -q -- "-b /dev" "${f}"; then
        sed -i "/-b \/dev/a\\        ${tmp_bind} \\\\" "${f}" 2>/dev/null && {
          msg -ts "Patched ${f##*/} with /tmp bind (method A)"
          continue
        }
      fi

      # Method B: insert after any existing -b line
      if grep -q -- "-b " "${f}"; then
        sed -i "0,/-b /s||-b |        ${tmp_bind} \\\\\n        -b |" "${f}" 2>/dev/null && {
          msg -ts "Patched ${f##*/} with /tmp bind (method B)"
          continue
        }
      fi

      # Method C: tell the user exactly what to add
      msg -tw "Could not auto-patch ${f##*/}"
      msg -a "  Manually add this line among the proot -b options:"
      msg -a "  ${tmp_bind} \\"
    fi
  done

  # 3. Create the one-command helper nh-x11
  local helper="${TERMUX_FILES_DIR}/usr/bin/nh-x11"
  cat > "${helper}" << 'X11HELPER'
#!/data/data/com.termux/files/usr/bin/bash
# nh-x11 — Launch Kali NetHunter desktop via Termux:X11 (low latency)
# Generated by Grok Build Powered NetHunter installer

# Kill any previous Termux:X11 instance
pkill -f "termux.x11" 2>/dev/null || true
sleep 0.5

# Start PulseAudio so the proot environment can reach it
pulseaudio --start \
  --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" \
  --exit-idle-time=-1 2>/dev/null || true

# Start Termux:X11 on display :0
export XDG_RUNTIME_DIR="${TMPDIR:-/data/data/com.termux/files/usr/tmp}"
termux-x11 :0 >/dev/null 2>&1 &
sleep 2

# Bring the Termux:X11 app to the foreground
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity >/dev/null 2>&1 || true
sleep 1

echo "[nh-x11] Termux:X11 is running on :0"
echo "[nh-x11] Launching desktop inside NetHunter..."

# Enter NetHunter and start the desktop environment.
# Default is XFCE. Change "startxfce4" below if you installed a different DE
# (e.g. startlxde, mate-session, startplasma-x11, etc.)
nethunter -r 'export DISPLAY=:0 PULSE_SERVER=127.0.0.1 XDG_RUNTIME_DIR=${TMPDIR} && su - kali -c "startxfce4"'
X11HELPER

  chmod 755 "${helper}"
  msg -ts "Created helper command: nh-x11"

  echo
  msg -a "  ${T}Usage after install:${S}"
  msg -a "    1. Install the Termux:X11 APK from GitHub nightly releases"
  msg -a "       (termux-x11-universal-debug.apk)"
  msg -a "    2. Run:  ${P}nh-x11${S}"
  msg -a "    3. The Termux:X11 window will open with the Kali desktop"
  echo
  msg -a "  ${T}Troubleshooting:${S}"
  msg -a "    Black screen → try: termux-x11 :0 -legacy-drawing"
  msg -a "    No sound     → make sure pulseaudio is running"
  msg -a "    Wrong DE     → edit /data/data/com.termux/files/usr/bin/nh-x11"
}
