#!/data/data/com.termux/files/usr/bin/bash
# GrokHunter — Termux:X11 low-latency desktop integration

setup_termux_x11() {
  msg -t "Setting up Termux:X11 (low-latency desktop)"

  # 1. Packages
  msg -tn "Installing x11-repo, termux-x11-nightly, pulseaudio..."
  if pkg install -y x11-repo >/dev/null 2>&1 && \
     pkg install -y termux-x11-nightly pulseaudio >/dev/null 2>&1; then
    cursor -u1
    msg -ts "Termux:X11 packages installed"
  else
    cursor -u1
    msg -tw "Some packages failed — run: pkg install x11-repo termux-x11-nightly pulseaudio"
  fi

  # 2. Patch nethunter / nh launcher for /tmp bind (required for X11 sockets)
  local launcher="${TERMUX_FILES_DIR}/usr/bin/nethunter"
  local shortcut="${TERMUX_FILES_DIR}/usr/bin/nh"
  local tmp_bind="-b /data/data/com.termux/files/usr/tmp:/tmp"

  for f in "${launcher}" "${shortcut}"; do
    [[ -f ${f} ]] || continue
    if grep -q "/data/data/com.termux/files/usr/tmp:/tmp" "${f}" 2>/dev/null; then
      msg -ts "${f##*/} already has /tmp bind"
      continue
    fi
    if grep -q -- "-b /dev" "${f}"; then
      sed -i "/-b \/dev/a\\        ${tmp_bind} \\\\" "${f}" 2>/dev/null && {
        msg -ts "Patched ${f##*/} with /tmp bind"
        continue
      }
    fi
    if grep -q -- "-b " "${f}"; then
      sed -i "0,/-b /s||-b |        ${tmp_bind} \\\\\n        -b |" "${f}" 2>/dev/null && {
        msg -ts "Patched ${f##*/} with /tmp bind (fallback)"
        continue
      }
    fi
    msg -tw "Could not auto-patch ${f##*/} — add manually: ${tmp_bind} \\"
  done

  # 3. Create nh-x11 helper
  local helper="${TERMUX_FILES_DIR}/usr/bin/nh-x11"
  cat > "${helper}" << 'X11HELPER'
#!/data/data/com.termux/files/usr/bin/bash
# nh-x11 — Launch Kali NetHunter desktop via Termux:X11 (low latency)
# Generated by GrokHunter

pkill -f "termux.x11" 2>/dev/null || true
sleep 0.5

pulseaudio --start \
  --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" \
  --exit-idle-time=-1 2>/dev/null || true

export XDG_RUNTIME_DIR="${TMPDIR:-/data/data/com.termux/files/usr/tmp}"
termux-x11 :0 >/dev/null 2>&1 &
sleep 2

am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity >/dev/null 2>&1 || true
sleep 1

echo "[nh-x11] Termux:X11 running on :0 — launching desktop..."
nethunter -r 'export DISPLAY=:0 PULSE_SERVER=127.0.0.1 XDG_RUNTIME_DIR=${TMPDIR} && su - kali -c "startxfce4"'
X11HELPER

  chmod 755 "${helper}"
  msg -ts "Created helper: nh-x11"

  echo
  msg -a "  ${T}Usage:${S}"
  msg -a "    1. Install Termux:X11 APK from GitHub nightly releases"
  msg -a "    2. Run:  ${P}nh-x11${S}"
  msg -a "  ${T}Tip:${S} Black screen → termux-x11 :0 -legacy-drawing"
}
